stages:
  - Package
  - Build

tarball:
  stage: Package
  image: alpine:latest
  before_script:
    - apk add --no-cache git make perl
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - make -f tools/star/Makefile
    - make -f tools/star/Makefile release VERSION=$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - release

moar:
  stage: Build
  image: alpine:latest
  before_script:
    - apk add --no-cache bash build-base git perl
    - cd "$(mktemp -d)"
    - tar xvf "$CI_PROJECT_DIR/release/rakudo-star-$CI_COMMIT_REF_NAME.tar.gz"
  script:
    - cd "rakudo-star-$CI_COMMIT_REF_NAME"
    - perl Configure.pl --prefix=/usr/local --backend=moar --gen-moar
  artifacts:
    paths:
      - "$CI_COMMIT_REF_NAME/release"
      - /usr/local

# TODO: Run tests
# TODO: Release an updated Docker container
# TODO: Release the tarball to some Raku server
