stages:
  - Package
  - Build

Tarball:
  stage: Package
  image: alpine:latest
  before_script:
    - apk add --no-cache git make perl
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - bin/mkrelease.sh "$CI_COMMIT_REF_NAME"
  artifacts:
    paths:
      - work/release

MoarVM:
  stage: Build
  image: alpine:latest
  before_script:
    - apk add --no-cache bash build-base git perl
    - cd -- "$(mktemp -d)"
    - tar xzf "$CI_PROJECT_DIR/work/release/rakudo-star-$CI_COMMIT_REF_NAME.tar.gz"
  script:
    - cd "rakudo-star-$CI_COMMIT_REF_NAME"
    - perl Configure.pl --prefix="$CI_PROJECT_DIR/work/install" --backend=moar --gen-moar --make-install
  artifacts:
    paths:
      - work/install

# TODO: Run tests
# TODO: Release an updated Docker container
# TODO: Release the tarball to some Raku server
