name: Docker Image CI

on:
  push:
    paths:
      - 'lib/docker/**.Dockerfile'
  pull_request:
    paths:
      - 'lib/docker/**.Dockerfile'
  workflow_dispatch:

jobs:
  varify_dockerfiles:
    runs-on: ubuntu-latest
    steps:
      
    # - name: Update Tools And Software
    #   run: sudo apt update && sudo apt upgrade && sudo apt install jq -y -qq

    - name: Check out code
      uses: actions/checkout@v4
      with:
        path: 'star'
        fetch-depth: 2
        ref: ${{ github.head_ref }}

    - name: Get Changed Dockerfiles
      id: changed-dockerfiles
      uses: tj-actions/changed-files@v47
      with:
        path: 'star'
        files: |
          **.Dockerfile

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-dockerfiles.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Build Docker Image(s)
      env:
        ALL_CHANGED_DOCKERFILES: ${{ steps.changed-dockerfiles.outputs.all_changed_files }}
        RSTAR_DEBUG: 1
      run: |
        for FILE in ${ALL_CHANGED_DOCKERFILES}; do
          echo "Will work on file \"$FILE\" now..."
          if ! [[ "$FILE" =~ "Dockerfile" ]]; then continue; fi
          IMAGE=$(basename -s ".Dockerfile" $FILE)
          echo "IMAGE is \"$IMAGE\""
          ls -l ./star/bin/rstar
          cd ./star
          bash ./bin/rstar build-docker $IMAGE
        done
