name: Test for alien 

on:
  workflow_dispatch:

env:
  RKD_REVISION: "01" # Change this if a build revision ever changes. 

jobs:
  run_alien:
    runs-on: ubuntu-latest

    steps:
    - name: Run alien
      run: |
        sudo apt update -qq && sudo apt upgrade -qq && sudo apt install -y -qq alien
        curl -s -O https://github.com/rakudo/star/releases/download/2025.01/rakudo-star-2025.01.tar.gz 
        for PKG in deb rpm; do
          sudo alien --to-${PKG} --description="Rakudo Star 2025.01" --version="2025.01" --target="x86_64" --veryverbose rakudo-star-2025.01.tar.gz
        done
        ls -la
